tap "devhubapp/devhub"
tap "domt4/autoupdate"
tap "eddieantonio/eddieantonio"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# tap "wantedly/tools", "git@github.com:wantedly/homebrew-tools"
brew "ack"
brew "act"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "asdf"
brew "bat"
brew "bison"
brew "icu4c"
brew "libpng"
brew "freetype"
brew "gettext"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "cmatrix"
brew "cowsay"
brew "nghttp2"
brew "openldap"
brew "curl"
brew "direnv"
brew "duti"
brew "editorconfig"
brew "guile"
brew "unbound"
brew "jpeg"
brew "fish"
brew "freetds"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "git"
brew "gnupg"
brew "tcl-tk"
brew "googler"
brew "imagemagick"
brew "jq"
brew "jupyterlab"
brew "kompose"
brew "krb5"
brew "libedit"
brew "libiconv"
brew "libpq"
brew "libxml2"
brew "libzip"
brew "mas"
brew "mcrypt"
brew "mkcert"
brew "neovim"
brew "nmap"
brew "node-build"
brew "nss"
brew "opencv"
brew "pigz"
brew "pipenv"
brew "postgresql", restart_service: true
brew "rcm"
brew "re2c"
brew "redis", restart_service: true
brew "rustup-init"
brew "sl"
brew "starship"
brew "tree"
brew "vercel-cli"
brew "w3m"
brew "yarn"
brew "zlib"
brew "eddieantonio/eddieantonio/imgcat"
brew "wantedly/tools/valec"
brew "wantedly/tools/valecjr"
cask "1password-beta"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "anki"
cask "cmd-eikana"
cask "devhub"
cask "discord"
cask "discord-canary"
cask "discord-ptb"
cask "displaperture"
cask "docker"
cask "dozer"
cask "drawio"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-sf-pro"
cask "forklift"
cask "gitkraken"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "hyper"
cask "insomnia"
cask "iterm2-beta"
cask "karabiner-elements"
cask "keka"
cask "keybase"
cask "keycastr"
cask "latest"
cask "logitech-options"
cask "mactex"
cask "mattermost"
cask "minecraft"
cask "notion"
cask "numi"
cask "obs"
cask "oracle-jdk"
cask "philips-hue-sync"
cask "postman"
cask "slack"
cask "spotify"
cask "tableplus"
cask "tower"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "vlc"
cask "zeplin"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Deliveries", id: 924726344
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "GoodNotes", id: 1444383602
mas "iA Writer", id: 775737590
mas "iMage Tools", id: 493949693
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
