tap "domt4/autoupdate"
tap "eddieantonio/eddieantonio"
tap "github/gh"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "act"
brew "libpng"
brew "autoconf"
brew "automake"
brew "bat"
brew "bison"
brew "freetype"
brew "gettext"
brew "glib"
brew "pkg-config"
brew "tbb"
brew "ceres-solver"
brew "cmatrix"
brew "libssh2"
brew "openldap"
brew "curl"
brew "freetds"
brew "gd"
brew "krb5"
brew "libpq"
brew "libzip"
brew "composer"
brew "coreutils"
brew "cowsay"
brew "direnv"
brew "duti"
brew "editorconfig"
brew "guile"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "harfbuzz"
brew "leptonica"
brew "srt"
brew "ffmpeg"
brew "ffmpeg@4"
brew "fish"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "ghq"
brew "git"
brew "glow"
brew "gnupg"
brew "gobject-introspection"
brew "googler"
brew "httpie"
brew "shared-mime-info"
brew "libheif"
brew "imagemagick"
brew "ipython"
brew "jpeg"
brew "jq"
brew "node", link: false
brew "jupyterlab"
brew "kompose"
brew "libedit"
brew "libiconv"
brew "libxml2"
brew "mas"
brew "mcrypt"
brew "mkcert"
brew "neovim"
brew "nghttp2"
brew "nmap"
brew "node-build"
brew "nss"
brew "numpy"
brew "vtk"
brew "opencv"
brew "pigz"
brew "pipenv"
brew "poppler"
brew "postgresql@14"
brew "python@3.9"
brew "qt"
brew "rcm"
brew "re2c"
brew "redis"
brew "rustup-init"
brew "sl"
brew "starship"
brew "tcl-tk"
brew "tree"
brew "vercel-cli"
brew "w3m"
brew "yarn"
brew "youtube-dl"
brew "zlib"
brew "eddieantonio/eddieantonio/imgcat"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "alacritty"
cask "anki"
cask "cmd-eikana"
cask "discord"
cask "displaperture"
cask "docker"
cask "dozer"
cask "drawio"
cask "eul"
cask "figma"
cask "firefox"
cask "firefox-developer-edition"
cask "firefox-nightly"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-pro"
cask "forklift"
cask "gitkraken"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-drive-file-stream"
cask "google-japanese-ime"
cask "hey"
cask "hyper"
cask "insomnia"
cask "iterm2-beta"
cask "karabiner-elements"
cask "keka"
cask "keybase"
cask "keycastr"
cask "kitty"
cask "logitech-options"
cask "mactex"
cask "mattermost"
cask "minecraft"
cask "monitorcontrol"
cask "notion"
cask "numi"
cask "obs"
cask "oracle-jdk"
cask "pdf-expert-beta"
cask "philips-hue-sync"
cask "postman"
cask "raindropio"
cask "raycast"
cask "slack"
cask "spotify"
cask "tableplus"
cask "tower"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "vlc"
cask "warp"
cask "zeplin"
cask "zoom"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Bear", id: 1091189122
mas "Craft", id: 1487937127
mas "Deliveries", id: 924726344
mas "egword Universal 2", id: 1272842196
mas "Gifski", id: 1351639930
mas "GoodNotes", id: 1444383602
mas "Hotspot Shield", id: 771076721
mas "iMage Tools", id: 493949693
mas "iMovie", id: 408981434
mas "Kindle", id: 405399194
mas "LINE", id: 539883307
mas "LookUp", id: 872564448
mas "Magnet", id: 441258766
mas "MeetingBar", id: 1532419400
mas "MindNode", id: 1289197285
mas "Pixelmator Pro", id: 1289583905
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Toggl Track", id: 957734279
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835
